version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE="your db name"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="your password"
      - MYSQL_ROOT_PASSWORD="your password"
